
# rustfmt.toml for base-traits
#
# Requires nightly rustfmt with unstable features enabled, e.g.:
#
#   ./scripts/fmt
#
# Or:
#
#   RUSTFMT="$(rustup which --toolchain nightly rustfmt)" cargo fmt -- --unstable-features

edition="2024"
style_edition="2024"

# array_width=60 # deprecated
# attr_fn_like_width=70 # deprecated
binop_separator="Front"
blank_lines_lower_bound=0
blank_lines_upper_bound=3 # default: 1
brace_style="SameLineWhere"
# chain_width=60 # deprecated
color="Auto"
combine_control_expr=false # default: true
comment_width=76 # default: 80
condense_wildcard_suffixes=false
control_brace_style="AlwaysSameLine"
disable_all_formatting=false
empty_item_single_line=false # default: true
enum_discrim_align_threshold=0
error_on_line_overflow=false
error_on_unformatted=false
# fn_args_layout="Vertical"
# fn_call_width=60 # deprecated
fn_params_layout="Vertical" # default: "Tall"
fn_single_line=false
force_explicit_abi=true
force_multiline_blocks=true # default: false
# force_code_in_doc_comments=true
format_macro_bodies=true
format_macro_matchers=true # default: false
format_strings=false
group_imports="Preserve"
hard_tabs=false
# hide_parse_errors=false
ignore=[
]
imports_granularity="Crate" # default: "Preserve"
imports_indent="Block"
imports_layout="Vertical" # default: "Mixed"
indent_style="Block"
inline_attribute_width=0
# license_template_path=""
match_arm_blocks=true
match_arm_leading_pipes="Preserve" # default: "Never"
match_block_trailing_comma=true # default: false
max_width=120 # default: 100
merge_derives=false # default: true
# merge_imports= # deprecated
newline_style="Auto"
normalize_comments=false
normalize_doc_attributes=true # default: false
overflow_delimited_expr=false
remove_nested_parens=true
reorder_impl_items=true # default: false
reorder_imports=true
reorder_modules=true
# report_fixme="Always"
# report_todo="Never"
# required_version="????"
short_array_element_width_threshold=1
# single_line_if_else_max_width=0 # deprecated
show_parse_errors=true
skip_children=false
space_after_colon=true
space_before_colon=true # default: false
spaces_around_ranges=false
struct_field_align_threshold=20
struct_lit_single_line=false
# struct_lit_trailing_comma="Vertical"
# struct_lit_width=0 # deprecated
# struct_trailing_comma="Vertical"
# struct_variant_width=0 # deprecated
tab_spaces=4
trailing_comma="Vertical"
trailing_semicolon=true
type_punctuation_density="Wide"
unstable_features=true
use_field_init_shorthand=true # default: false
use_small_heuristics="Default"
use_try_shorthand=true # default: false
# version=
where_single_line=false
wrap_comments=false

